name: Linting Check

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install htmlhint stylelint

      - name: Lint HTML
        run: npx htmlhint "src/**/*.html"

      - name: Lint CSS
        run: npx stylelint "styles/**/*.css"
